# Generated by Django 5.2 on 2025-05-15 01:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_rename_payment_intent_order_merchant_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='merchant_id',
            new_name='payment_intent',
        ),
    ]
